### ISSUE TITLE
Не верные варианты ответов

### ISSUE THREAD

**Issue by AbushkevichGrisha** [pythontutor/pythontutor-ru#115]
2. Условная инструкция<br>
Задача "Високосный год"<br>
Условия:<br>
![image](https://cloud.githubusercontent.com/assets/16192207/11630109/0ade8d34-9d0d-11e5-842b-6eebe2b433e5.png)
Варианты ответов:<br>
![image](https://cloud.githubusercontent.com/assets/16192207/11630132/1bcc2c8c-9d0d-11e5-8d2e-1a3b60857109.png)

Последние годы столетий, оканчивающиеся на два нуля, в трёх случаях из четырёх не являются високосными. Так, годы 1700, 1800 и 1900 не являются високосными, так как они кратны 100 и не кратны 400. Годы 1600 и 2000 — високосные, так как они кратны 400. Годы 2100, 2200 и 2300 — невисокосные. В високосные годы вводится дополнительный день — 29 февраля.

**Comment by Funghorn** [comment]
А что неправильного в условии? Годы 1700, 1800 и 1900 невисокосные, и в результате и должно быть 1700 - NO, 1800 - NO, 1900 - NO.
