### ISSUE TITLE
Занятие 3. Операции с целыми и вещественными числами Задача «Число десятков»

### ISSUE THREAD

**Issue by arturpanteleev** [pythontutor/pythontutor-ru#118]
from math import *

a = int(input());

print((a - (a % 10)) // 10)
_____________________

Если нажимать "Запустить" то исполняет корректно и получаем нужные выходные даннные.
А вот при попытке сдать работу получается фигня какая то

**Comment by vpavlenko** [comment]
Проверил со своего обычного аккаунта - у меня всё сдалось. У вас осталась проблема? Какой браузер?

Если хромоподобный браузер, то пожалуйста:
- Откройте Инструменты разработчика (Chrome DevTools)
- Перейдите на вкладку Network
- Нажмите кнопку Отправить на странице задачи
- Найдите в списке слева внизу строку sumbit/ и кликните на неё
- Сделайте скриншот экрана и приложите сюда

**Comment by arturpanteleev** [comment]
[image: Inline image 1]
Пожалуйста)


2015-12-13 14:15 GMT+07:00 Vitaly Pavlenko <notifications@github.com>:

**Comment by vpavlenko** [comment]
Картинка не прикрепилась :с

**Comment by arturpanteleev** [comment]
[image: Inline image 1]

**Comment by arturpanteleev** [comment]
https://mail.google.com/mail/u/0/?ui=2&ik=08b7a9f052&view=fimg&th=151a0272879d9e13&attid=0.1&disp=emb&realattid=ii_151a026ad3321a37&attbid=ANGjdJ_wnt0nDU7eFKM9yE7NJm3WibehZ-3eBrP1GJ8ZXvgeaMTmGbxKv34DAzXdZPC_V3UCgR7K9EQOO73mwjUc-aj4lR-9fr2t9a1cTnVhd-k7z-4UB-McYFotZyw&sz=s0-l75-ft&ats=1450090902100&rm=151a0272879d9e13&zw&atsh=1

вот так на худой конец уж

**Comment by vpavlenko** [comment]
403 Forbidden до картинки. Проверьте, что ваша ссылка открывается из режима Инкогнито.

**Comment by arturpanteleev** [comment]
https://gm1.ggpht.com/ztwF5ydDy7KdqtUwjaZ0ZjGvU2AI9eBABwwoPNKMkw1wa1EC7RjUjVXqXA52vlj2sM0nDelnXg6eCyXVJs89kQjH_LAACWZEXNiuQTGh68C2kQrsXNASON5ZGuruOJZV0tbISbKsePZe3dQhiAtb7LIcJGIaOAqR9zPqlnPdyJ8UkLemjdzF6sEFcPihNL6xhkm9ymnzkPmV91sImhM1xkgFWlG7fkzxLLz2L88VvsGRb73-KOzdfCcguC6JsaAoKNOxl1IqGS3I27o56-M75Fg4gxYOKPU662mPYPFkTix-JN_Yj8ejtllsIlE4siv5bUwM7L_7rMaCEjFO-i2pnqgbHFUzgNEYrTMpu0VyBmGT-tZEmFeAsKfUn2cxKos7wkf_N11eqd06OOH4USpNic9-AmRIz7suiENFRfiJkDLpDmmnNZXsAw0DEeaL7kXCJgcrei1-81_M7txZQdb6z918Ks6Ol31l-h7chr64wqw1WO5EDFM9sW1sunfIu7LmzyB2Syo2O1y8uO-2J_jXJ8AOFsTyFsMufosR_zvffvHePAJc-yNRJ_qpp_7jOXFL45Qb4U7OTp6TN5WT9U3PVXaA445bY1dwWGVuVQTovw5_W_0YX5pwWXjM5k6kf4aDrbluXoll0eobeipv768IdHXP_BU1FPZZVGlEEue-qYzR=s0-l75-ft-l75-ft

вот эта из другого браузера открылась и с телефона

2015-12-14 18:03 GMT+07:00 Vitaly Pavlenko <notifications@github.com>:

**Comment by vpavlenko** [comment]
Проверьте _из_режима_инкогнито_, в котором вы не залогинены в ваш гугловый аккаунт. Насколько я понимаю, вы сохраняете картинку в на Гугл.Диске в папке, в которую ни у кого кроме вас нет доступа. Тестировать доступ с ваших браузеров, в которых вы залогинены в Гугле, нет смысла. Вот что я вижу по последней ссылке:
![2015-12-14 14-09-55 error 403 forbidden 1](https://cloud.githubusercontent.com/assets/1491908/11779509/989e21d4-a26c-11e5-8a35-c8e06966b7f5.png)

**Comment by arturpanteleev** [comment]
я не залогинен в гугле ни в фаерфоксе,  ни в телефоне. Иначе бы я не стал
там проверять. И картинка не с диска, а просто скриншот, я не знаю почему
вы его не моете принять. ВЫ уверены что у вас отображение картинок включено
в почте?



2015-12-14 18:11 GMT+07:00 Vitaly Pavlenko <notifications@github.com>:

**Comment by vpavlenko** [comment]
Я проверяю не из почты, я кликаю на ссылку из Гитхаба.

**Comment by arturpanteleev** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/7831658/11779732/aaeaaa56-a28f-11e5-9dd3-4019245530ba.png)

**Comment by vpavlenko** [comment]
Ага, спасибо.

1) Пролистайте саму страницу задачи после сданного решения вниз, посмотрите визуально - все рожицы зелёные, нет ни одной красной? Если есть красная, то этот тест падает, его надо отлаживать. В базе все ваши посылки помечены как проваливающие хотя бы один тест.

2) Если все рожицы зелёные, то, пожалуйста, сделайте тот же скриншот, что я просил, только после выбора "submit/" для него выберите вкладке Response:
![aaeaaa56-a28f-11e5-9dd3-4019245530ba 2](https://cloud.githubusercontent.com/assets/1491908/11780461/29c6dd4e-a273-11e5-9f47-1815b2a66c8e.png)

**Comment by arturpanteleev** [comment]
{"fail_test": 9, "tests": ["ok", "ok", "ok", "ok", "ok", "ok", "ok", "ok",
"ok", "wrong_answer", "wrong_answer", "wrong_answer", "wrong_answer",
"wrong_answer", "wrong_answer", "ok", "ok", "ok"], "status": "error"}
Такой ответ приходит. Ну и рожицы соответственно понятно где красные)

2015-12-14 18:58 GMT+07:00 Vitaly Pavlenko <notifications@github.com>:

**Comment by vpavlenko** [comment]
Вот по красным строчкам используя кнопку в начале строки можно проиграть код на этом тесте. Успешной отладки :)

**Comment by GHMember** [comment]
В задании сказано "Обратите внимание, что функция round не годится для этой задачи!"
Эталонный ответ:
`x = float(input())
    if x - int(x) == 0.5:
    x += 0.1
print(round(x))`

Это не противоречит условию задачи?
