### ISSUE TITLE
Хорошо бы сохранять значения переменных на всех итерациях

### ISSUE THREAD

**Issue by gektor34** [pythontutor/pythontutor-ru#121]
Хорошо бы сохранять значения переменных на всех итерациях, например:
i | j | n
0 0  1
0 1  2
0 2  3
будет легче отлаживать программы.

**Comment by vpavlenko** [comment]
Можно в каждой строчке показывать вычисленное в ней значение. Это дико сложно сделать, но и дико круто будет. Это скорее к авторам pythontutor.com
