### ISSUE TITLE
Словари!

### ISSUE THREAD

**Issue by Zodt** [pythontutor/pythontutor-ru#147]
Задача "Продажи":
Вы издеваетесь? Каким образом я должен был правильно написать код, если про модуль collections в самой статье нет ни слова?!?!?! А по-другому задачу не решить! Браво ребята, молодцы, с Вас новый стул, тк старый спалил мой пукан из-за этой задачи! И так блин во всей 15-й главе! Либо инфы в статью добавляйте, либо задачи делайте другие!

**Comment by iLizardKing** [comment]
как считать все строки до конца? исключения использовать?
