### ISSUE TITLE
Задача «Сумма N чисел»

### ISSUE THREAD

**Issue by violinist2** [pythontutor/pythontutor-ru#150]
Интересно увидеть варианты решений

**Comment by violinist2** [comment]
sum = 0
sum = int(input())
a = sum
for i in range(sum):
    n =int(input())   
    sum += n  
print(sum - a)

**Comment by idrummer83** [comment]
воспользовался вашим решением, но саму задачу так и не понял.

**Comment by facafaca57** [comment]
n = int(input())
sum = 0
for i in range(n):
    n = int(input())
    sum += n
print (sum)
