### ISSUE TITLE
Занятие 4. Цикл for Задача «Количество нулей»

### ISSUE THREAD

**Issue by violinist2** [pythontutor/pythontutor-ru#151]
# решение, которое прошло(но заняло не мало времени)) может кому пригодится
n = int(input())
sum = 0
y = 0
mn = 0

for i in range(1, n + 1, mn + 1 ):
  mn = int(input())
  mn+=0
  if mn == 0 :
   y += 1
print(y)

**Comment by Phantomrus** [comment]
1) Переменная sum не используется, 
2) mn объявляется равной нулю и используется в цикле for только для того, чтобы задать шаг равный 1, хотя это значение по умолчанию
3) Зачем нужна строчка mn+=0?

Удаляем sum и mn+=0, for равносилен виду **for i in range(1, n + 1, 0 + 1 )**. а это равносильно виду **for i in range(1, n + 1)**, а это равносильно **for i in range(n)**

Уже получается более читаемо:
```
n = int(input())
y = 0
mn = 0

for i in range(n):
    mn = int(input())
    if mn == 0 :
        y += 1
print(y)
```

Теперь, можем избавиться от mn, так как он используется только в одном месте:
```
n = int(input())
y = 0

for i in range(n):
    if int(input()) == 0 :
        y += 1
print(y)
```

Последним шагом избавляемся от переменной n? добавляя input сразу в range() в цикле for:
```
y = 0
for i in range(int(input())):
    if int(input()) == 0:
        y += 1
print(y)
```

Пять строчек вместо десяти и понятные операции (без mn += 0)

**Comment by Nikonorich** [comment]
Почему обязательно for i in range(INT(INPUT()))
почему не работает так:
sum=0
N=int(input())
for i in range (N):
    if N==0:
        sum+=1
print(sum)
