### ISSUE TITLE
Операции с целыми и вещественными числами. Задача  Часы 1

### ISSUE THREAD

**Issue by livorish** [pythontutor/pythontutor-ru#156]
Так в принципе тоже можно:
H = int(input()) #час
M = int(input()) #минуты
S = int(input()) #секунды
hour = ( 60 * H + M + (S / 60) ) / 2 # 1 hour = 30 C
print(hour)

**Comment by 12oad** [comment]
h = int(input())
m = int(input())
s = int(input())

mins = m + s / 60                        # минуты + (минуты из сек)
hours = (h + mins / 60) % 12      # часы + (часы из мин)

print(hours * 30)                          # 1 час - 30°
