### ISSUE TITLE
Занятие 1. Электронные Часы.

### ISSUE THREAD

**Issue by 12oad** [pythontutor/pythontutor-ru#158]
Добрый день.
> _Дано число n. С начала суток прошло n минут. Определите, сколько часов и минут будут показывать электронные часы в этот момент. Программа должна вывести два числа: количество часов (от 0 до 23) и количество минут (от 0 до 59). Учтите, что число n может быть больше, чем количество минут в сутках._

n = int(input())
hours = n // 60
mins = n % 60

print(hours, mins)
____________________

Как дальше ? Спс.

**Comment by Polumonokok** [comment]
используй hours = n % (60 * 24) // 60

**Comment by 12oad** [comment]
> используй hours = n//60%24
Умно! Я как-то не догадался, и вообще не догадываюсь никогда, если задача посложнее. Спс бро.

**Comment by GFedorow** [comment]
Для конкретной задачи, чтобы ответ был засчитан:
n = int(input())

print(n//60%24)
print(n%60)
Иначе не примет, все проблемы в том, что часто не соответствует требуемое на выходе :(
условию самой задачи.
