### ISSUE TITLE
 Занятие 4. Цикл for Задача «Ряд - 3»

### ISSUE THREAD

**Issue by Vapekreng** [pythontutor/pythontutor-ru#159]
В условии сказано не использовать инструкцию if, а в эталонном решении она присутствует. Может я чего-то не понимаю? Мой вариант решения:
a=int(input())
b=int(input())
a=a-(a+1)%2
for i in range(a,b-1,-2):
    print(i)

**Comment by 12oad** [comment]
+1 Поддерживаю. Моё тоже похоже.

> a = int(input())
> b = int(input())
> 
> d = a % 2 - 1
> 
> for i in range(a+d, b-1, -2):
>     print(i)

**Comment by AlexStel** [comment]
A=int(input())
B=int(input())
for i in range(A+A%2-1,B-1,-2):
    print(i)
