### ISSUE TITLE
задача 7. Страны и города. Словари

### ISSUE THREAD

**Issue by sashnat** [pythontutor/pythontutor-ru#165]
Друзья, не понятно, почему при выполнении второго цикла обрабатывается только последняя  часть множества set(city). И, как результат, получаем только один  ответ. 
На мой взгляд задача несложная, но почему-то "не идет" ...
Заранее спасибо.

d = {}
 i in range(int(input())):
    country, *city = input().split() # * - объединение элементов
    d[country] = set(city)

d1 = {}
for i in range(int(input())):
    city = input()
    d1[i] = city
    if d1[i] in d[country]:
        print(country)

**Comment by 12oad** [comment]
Тум-турум. Я еще до словарей не дошел. Как дойду - помогу =) 

Успехов в учёбе вам.

**Comment by sashnat** [comment]
12oad, спасибо =)
