### ISSUE TITLE
Задача «Потерянная карточка»

### ISSUE THREAD

**Issue by smeshny** [pythontutor/pythontutor-ru#168]
http://pythontutor.ru/lessons/for_loop/problems/lost_card/
Программа выполняет все входные условия, но проверку не проходит. Очень странно.

```
N = int(input())
sum_all = 0
sum_k = 0
for i in range(1, N + 1):
    sum_all += i
for i in range(1, N):
    n = input()
    sum_k += n
print (sum_all - sum_k)
```

**Comment by 12oad** [comment]
Введённое с помощью input() преобразуется в строку.

5 -> input() == '5'

**Comment by idrummer83** [comment]
n = int(input())
