### ISSUE TITLE
Упростить систему комментирования

### ISSUE THREAD

**Issue by nameup** [pythontutor/pythontutor-ru#180]
Если нет возможности комментариев прямо на сайте, хотя бы добавить комментарии из соц сетей.
Вы сами тестировали комментирование через Дискус? Даже при авторизации через социальные сети приходится регистрироваться на Д. отдельно. Т.е. двойная авторизация. 

Хотя бы уберите требование пароля в дискусе, достаточно почты. 
Спасибо.

**Comment by vpavlenko** [comment]
убрали комментарии вообще
https://vk.com/pythontutor?w=wall-95589554_39
