### ISSUE TITLE
Для каких ещё языков существуют интепретаторы, которые можно встроить в систему?

### ISSUE THREAD

**Issue by vpavlenko** [pythontutor/pythontutor-ru#7]

**Comment by mig19** [comment]
SWI-Prolog.
Prolog-tutor  http://www.swi-prolog.org/  я бы с удовольствием бы использовал бы на занятиях бы по логическому программированию.
Есть более простая русская версия Пролог-Д.
Готов подготовить тексты занятий и набор задач.
С уважением, М.Н. Алексеев, Челябинск
