### ISSUE TITLE
Кажется программа где-то ошибается

### ISSUE THREAD

**Issue by crabman448** [pythontutor/pythontutor-ru#93]
Если запустить компилятор, то показывает 35, а в итоге пишет, что ошибка

![2015-10-08 13 11 49](https://cloud.githubusercontent.com/assets/7022709/10363615/3281b8b2-6dbe-11e5-8d43-400129946631.png)
![2015-10-08 13 11 45](https://cloud.githubusercontent.com/assets/7022709/10363616/32853758-6dbe-11e5-96b8-9331afb118a3.png)

**Comment by seeker27** [comment]
Ошибается не программа, а Ваш алгоритм. В одном из классов не хватит одной парты в Вашем случае. Нельзя сразу суммировать всех учеников третих классов, можно так:
c1=int(input())
c2=int(input())
c3=int(input())
t=c1//2+c1%2+c2//2+c2%2+c3//2+c3%2
print(t)

Хотя я решил так:
c1=(int(input())+1)//2
c2=(int(input())+1)//2
c3=(int(input())+1)//2
t=c1+c2+c3
print(t)

**Comment by crabman448** [comment]
https://github.com/seeker27

**Comment by crabman448** [comment]
Все, понял фишку задания и свою ошибку) Спасибо!
